services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    image: alexhamidi/graphit:1.0
    container_name: backend
    ports:
      - "8080:8080"
